name: monetary-transmission
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - openpyxl
  - statsmodels
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pip:
      - torch
      - tensorflow
      - papermill
